@startuml
title Sequence Diagram for AddItemCommand (Single-Category Parsing and Command Creation)

autonumber
hide footbox

participant ":AddCommandParser" as AddCommandParser
participant ":AddItemCommandParser" as AddItemCommandParser
participant ":InputValidator" as InputValidator
participant ":CommonFieldParser" as CommonFieldParser
participant ":BooleanFieldParser" as BooleanFieldParser

AddCommandParser -> AddItemCommandParser: handleFruit(trimmedInput)
activate AddItemCommandParser

AddItemCommandParser -> InputValidator: validate(input, ...)
activate InputValidator
InputValidator --> AddItemCommandParser
deactivate InputValidator

AddItemCommandParser -> CommonFieldParser: parse(input, "isRipe/")
activate CommonFieldParser
CommonFieldParser --> AddItemCommandParser: commonFields
deactivate CommonFieldParser

AddItemCommandParser -> BooleanFieldParser: parse(input, "isRipe/")
activate BooleanFieldParser
BooleanFieldParser --> AddItemCommandParser: isRipe
deactivate BooleanFieldParser

create ":AddItemCommand" as AddItemCommand
AddItemCommandParser -> AddItemCommand: 5 AddItemCommand(categoryName, item)
activate AddItemCommand
AddItemCommand --> AddItemCommandParser: 6 command
deactivate AddItemCommand

AddItemCommandParser --> AddCommandParser: command
deactivate AddItemCommandParser
@enduml

