@startuml
title Sequence Diagram for ListCommand (Parse and Command Creation)

autonumber
hide footbox

actor User
participant ":UI" as UI
participant ":InventoryDock" as InventoryDock
participant ":Parser" as Parser
participant ":ListCommand" as ListCommand

User -> UI: enter list command
activate UI
UI -> InventoryDock: input
activate InventoryDock
InventoryDock -> Parser: parse(input)
activate Parser
create ListCommand
Parser -> ListCommand: ListCommand()
activate ListCommand
ListCommand --> Parser: command
deactivate ListCommand
Parser --> InventoryDock: command
deactivate Parser
deactivate InventoryDock
deactivate UI
@enduml
